### ISSUE TITLE
Save subscriptions on change

### ISSUE THREAD

**Issue by david-i-berry** [wmo-im/wis2downloader#12]
Topics added to the active subscriptions need to be saved so that on restart the user does not need to re-subscribe manually.

**Comment by maaikelimper** [comment]
create topics.json with topics separate from config.json

**Comment by david-i-berry** [comment]
Example json file:

```
{
    "topics": {
        "origin/a/wis2/+/data/core/weather/surface-based-observations/synop": "$TOPIC"
    }, 
    "client_id": "20363bd5-d436-40ee-a60f-b135076b6bec"
}
```

I've included a client / session id for persisting between runs.
