### ISSUE TITLE
wis2-downloader filename should not derive filename from URL used in message, also to avoid duplicates

### ISSUE THREAD

**Issue by maaikelimper** [wmo-im/wis2downloader#14]
While subscribing to cache-topic, I received the following:
![image](https://github.com/wmo-im/wis2-downloader/assets/19169339/041de045-d241-4a66-b819-b2c906a25653)

The difference in file-extension is due to the difference caches using different approaches for the download-url ...

We need to use the data_id to name the file, as this is the only value that uniquely identifies the data. 

Also to avoid downloading the same data twice as the filename is used for de-duplication:
https://github.com/wmo-im/wis2-downloader/blob/6d1611be1de1724b85cccf64bec0784d7cf2c6ac/wis2downloader/downloader/__init__.py#L127-L135

**Comment by david-i-berry** [comment]
hash (sha256) of data id used as the filename. Extension set based on link type, mapping performed by:

https://github.com/wmo-im/wis2-downloader/blob/4eded2bcfdb88ab63b1646c0c9005d1e3800cacd/wis2downloader/downloader/__init__.py#L75-L86

**Comment by david-i-berry** [comment]
@maaikelimper can we close following the decision to keep with the filename and reopen if necessary?
