### ISSUE TITLE
broker_url should be broker_host

### ISSUE THREAD

**Issue by maaikelimper** [wmo-im/wis2downloader#15]
In the configuration of wis2-downloader a user has to define "broker_url", "broker_port" and "protocol"

URL would be defined including the port and protocol, for  example: `mqtts://globalbroker.meteo.fr:8883` , instead the broker_url should be broker_host in the way it is used in wis2-downloader ....

**Comment by david-i-berry** [comment]
Variables renamed to:

```
{
    ...
    "broker_hostname": "globalbroker.meteo.fr",
    "broker_password": "everyone",
    "broker_port": 443,
    "broker_protocol": "websockets",
    "broker_username": "everyone",
    ...
}
```

**Comment by maaikelimper** [comment]
https://github.com/wmo-im/wis2downloader/pull/18
